service: recharge-playwright-nestjs

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  profile: default
# plugins:
#   - serverless-offline

functions:
  index:
    handler: main.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any