name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare

  deploy:
    needs: prepare
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare

      - run: |
          set -x
          pnpm nx build recharge-playground
          cp apps/recharge-playground/serverless.yml dist/apps/recharge-playground/
          cd dist/apps/recharge-playground/
          npm install --prod
          	
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sls deploy
