name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare:
    name: Prepare

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        app:
          - recharge-playground
          - payment-service
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare

      - name: Deploy application
        run: |
          set -x
          APP=${{ matrix.app }}
          pnpm install serverless -g
          pnpm nx build ${APP}
          cp apps/${APP}/serverless.ts dist/apps/${APP}/
          cd dist/apps/${APP}/
          # todo use pnpm
          npm install --prod
            
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sls deploy --stage=dev
